### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by V00ster1** [kraanzu/termtyper#13]
$ python -m pip install git+https://github.com/kraanzu/termtyper.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/kraanzu/termtyper.git
  Cloning https://github.com/kraanzu/termtyper.git to /tmp/pip-req-build-63zj3e79
  Running command git clone -q https://github.com/kraanzu/termtyper.git /tmp/pip-req-build-63zj3e79
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
WARNING: Keyring is skipped due to an exception: g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 316, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 454, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 348, in resolve
    failure_causes = self._attempt_to_pin_criterion(name, criterion)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 208, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 200, in _get_criteria_to_update
    name, crit = self._merge_into_criterion(r, parent=candidate)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 176, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/lib/python3.10/site-packages/resolvelib/resolvers.py", line 83, in from_requirement
    if not cands:
  File "/usr/lib/python3.10/site-packages/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 99, in __bool__
    return any(self)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 218, in iter_index_candidates
    result = self._finder.find_best_candidate(
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 872, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 815, in find_all_candidates
    package_links = self.process_project_url(
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 779, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 617, in fetch_page
    return _get_html_page(location, session=self.session)
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 429, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "/usr/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 126, in _get_html_response
    resp = session.get(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.10/site-packages/pip/_internal/network/session.py", line 424, in request
    return super().request(method, url, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 687, in send
    r.content
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3.10/site-packages/urllib3/response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.10/site-packages/urllib3/response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/home/asus/.local/lib/python3.10/site-packages/cachecontrol/filewrapper.py", line 96, in read
    self._close()
  File "/home/asus/.local/lib/python3.10/site-packages/cachecontrol/filewrapper.py", line 76, in _close
    self.__callback(result)
  File "/home/asus/.local/lib/python3.10/site-packages/cachecontrol/controller.py", line 353, in cache_response
    self._cache_set(cache_url, request, response, body, expires_time)
  File "/home/asus/.local/lib/python3.10/site-packages/cachecontrol/controller.py", line 272, in _cache_set
    self.cache.set(
TypeError: SafeFileCache.set() got an unexpected keyword argument 'expires'

**Comment by kraanzu** [comment]
Hi @V00ster1, This is a known issue on arch
You can try to reinstall pip
Here are the steps: https://github.com/pypa/pip/issues/10750#issuecomment-1001222324
and let me know if this works :)

**Comment by V00ster1** [comment]
It works! Thanks :)
